//CONSTANTE       //STRING
export const VIEW_USERNAME = 'VIEW_USERNAME';
export const GET_COMPANIES = 'GET_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const GET_CURRENT_PROJECT = 'GET_CURRENT_PROJECT';