//CONSTANTE       //STRING
//TYPES OF COMPANIES
export const VIEW_USERNAME = 'VIEW_USERNAME';
export const GET_COMPANIES = 'GET_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const GET_CURRENT_PROJECT = 'GET_CURRENT_PROJECT';
export const LEAVE_COMPANY = 'LEAVE_COMPANY';
//TYPES OF PRODUCTS
export const PRODUCTS_COMPANY = 'PRODUCTS_COMPANY';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const VALIDATE_PRODUCTS = 'VALIDATE_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const GET_CURRENT_PRODUCTS = 'GET_CURRENT_PRODUCTS';
export const ACTUALIZAR_PRODUCTO = 'ACTUALIZAR_PRODUCTO';